# Generated by Django 2.2.3 on 2019-07-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0002_auto_20190730_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_valide',
            new_name='is_valid',
        ),
    ]
