# Generated by Django 2.2.3 on 2019-08-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0008_user_crops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='crops',
            field=models.ManyToManyField(null=True, related_name='users', to='farmster_server.Crop'),
        ),
    ]
