# Generated by Django 2.2.3 on 2019-08-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0009_auto_20190804_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='farmster_server.Place'),
        ),
    ]
