# Generated by Django 2.2.3 on 2019-08-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0010_auto_20190805_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='farmster_server.Agent'),
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(default='IL', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='location_lat',
            field=models.FloatField(default=123343.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='location_lon',
            field=models.FloatField(default=553311),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('VILLAGE', 'VILLAGE'), ('TOWN', 'TOWN'), ('CITY', 'CITY'), ('OTHER', 'OTHER')], default='UNKNOWN', max_length=255),
        ),
    ]
