# Generated by Django 2.2.3 on 2019-08-06 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0012_auto_20190806_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_place_users', to='farmster_server.Place'),
        ),
        migrations.CreateModel(
            name='CropListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('amount_unit', models.CharField(choices=[('KGS', 'KGS'), ('TONS', 'TONS'), ('BOXES', 'BOXES'), ('OTHER', 'OTHER')], default='KGS', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED'), ('SOLD', 'SOLD'), ('CANCELLED ', 'CANCELLED ')], default='ACTIVE', max_length=255)),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_listings', to='farmster_server.Crop')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_listings', to='farmster_server.Place')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
