# Generated by Django 2.2.3 on 2019-08-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0013_auto_20190809_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_app_user',
        ),
        migrations.AddField(
            model_name='place',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
