# Generated by Django 2.2.3 on 2019-08-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0014_user_favorite_crop_listings'),
        ('farmster_server', '0014_auto_20190809_1610'),
    ]

    operations = [
    ]
