# Generated by Django 2.2.3 on 2019-08-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0017_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='agent',
        ),
        migrations.AddField(
            model_name='place',
            name='agents',
            field=models.ManyToManyField(related_name='places', to='farmster_server.Agent'),
        ),
    ]
