# Generated by Django 2.2.3 on 2019-08-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0018_auto_20190812_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('GROUP', 'GROUP'), ('VILLAGE', 'VILLAGE'), ('TOWN', 'TOWN'), ('CITY', 'CITY'), ('OTHER', 'OTHER')], default='UNKNOWN', max_length=255),
        ),
    ]
