# Generated by Django 2.2.3 on 2019-08-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0019_auto_20190812_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='croplisting',
            old_name='user',
            new_name='farmer',
        ),
        migrations.RemoveField(
            model_name='croplisting',
            name='place',
        ),
    ]
