# Generated by Django 2.2.3 on 2019-08-12 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0020_auto_20190812_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croplisting',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_listings', to='farmster_server.Farmer'),
        ),
    ]
