# Generated by Django 2.2.3 on 2019-08-14 08:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0021_auto_20190812_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_phone_number', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='croplisting',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED'), ('SOLD', 'SOLD'), ('CANCELLED', 'CANCELLED')], default='ACTIVE', max_length=255),
        ),
        migrations.CreateModel(
            name='DealPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipping_method', models.CharField(choices=[('PICKUP', 'PICKUP'), ('DELIVERY', 'DELIVERY')], default='PICKUP', max_length=255)),
                ('price', models.FloatField()),
                ('pricing_type', models.CharField(choices=[('TOTAL', 'TOTAL'), ('PER_KG', 'PER_KG')], default='PER_KG', max_length=255)),
                ('amount', models.FloatField()),
                ('amount_unit', models.CharField(choices=[('KGS', 'KGS'), ('TONS', 'TONS'), ('BOXES', 'BOXES'), ('OTHER', 'OTHER')], default='KGS', max_length=255)),
                ('crop_quality', models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('POOR', 'POOR'), ('GOOD', 'GOOD'), ('EXCELLENT', 'EXCELLENT')], default='UNKNOWN', max_length=255)),
                ('crop_size', models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM'), ('LARGE', 'LARGE')], default='UNKNOWN', max_length=255)),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_parts', to='farmster_server.Crop')),
                ('deal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_parts', to='farmster_server.Deal')),
            ],
        ),
    ]
