# Generated by Django 2.2.3 on 2019-08-14 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0022_auto_20190814_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to=settings.AUTH_USER_MODEL),
        ),
    ]
