# Generated by Django 2.2.3 on 2019-08-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0023_deal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='farmers',
            field=models.ManyToManyField(related_name='users', to='farmster_server.Farmer'),
        ),
        migrations.AlterField(
            model_name='croplisting',
            name='amount_unit',
            field=models.CharField(choices=[('KGS', 'KGS'), ('TONS', 'TONS'), ('BOXES', 'BOXES'), ('TRUCKS', 'TRUCKS'), ('OTHER', 'OTHER')], default='KGS', max_length=255),
        ),
        migrations.AlterField(
            model_name='dealpart',
            name='amount_unit',
            field=models.CharField(choices=[('KGS', 'KGS'), ('TONS', 'TONS'), ('BOXES', 'BOXES'), ('TRUCKS', 'TRUCKS'), ('OTHER', 'OTHER')], default='KGS', max_length=255),
        ),
    ]
