# Generated by Django 2.2.3 on 2019-08-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0025_auto_20190818_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealpart',
            name='currency',
            field=models.CharField(default='KES', max_length=3),
            preserve_default=False,
        ),
    ]
