# Generated by Django 2.2.3 on 2019-08-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0025_auto_20190818_1209'),
        ('farmster_server', '0027_place_district'),
    ]

    operations = [
    ]
