# Generated by Django 2.2.3 on 2019-08-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0028_merge_20190821_1651'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('name', 'district'), name='unique_name_district'),
        ),
    ]
