# Generated by Django 2.2.3 on 2019-09-03 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0029_auto_20190821_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='seller_phone_number',
        ),
        migrations.AddField(
            model_name='deal',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='farmster_server.Farmer'),
        ),
    ]
