# Generated by Django 2.2.3 on 2019-09-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0030_auto_20190903_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
