# Generated by Django 2.2.3 on 2019-09-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0031_auto_20190922_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
