# Generated by Django 2.2.3 on 2019-10-21 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0034_auto_20191007_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croplisting',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_listings', to='farmster_server.Crop'),
        ),
        migrations.AlterField(
            model_name='croplisting',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_listings', to='farmster_server.Farmer'),
        ),
    ]
