# Generated by Django 2.2.3 on 2019-10-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0035_auto_20191021_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='district_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='district_sw',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
