# Generated by Django 2.2.3 on 2019-10-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0036_auto_20191030_1616'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='place',
            name='unique_name_district',
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('name_en', 'district_en'), name='unique_name_district_en'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('name_sw', 'district_sw'), name='unique_name_district__sw'),
        ),
    ]
