# Generated by Django 2.2.3 on 2019-10-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0037_auto_20191030_1619'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='place',
            name='unique_name_district_en',
        ),
        migrations.RemoveConstraint(
            model_name='place',
            name='unique_name_district__sw',
        ),
        migrations.RemoveField(
            model_name='place',
            name='district_en',
        ),
        migrations.RemoveField(
            model_name='place',
            name='district_sw',
        ),
        migrations.RemoveField(
            model_name='place',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='place',
            name='name_sw',
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('name', 'district'), name='unique_name_district'),
        ),
    ]
