# Generated by Django 2.2.3 on 2020-11-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0039_auto_20191030_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('otp', models.CharField(max_length=6)),
                ('otp_start', models.DateTimeField()),
                ('otp_end', models.DateTimeField()),
                ('expired', models.BooleanField(default=False)),
                ('phone_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
