# Generated by Django 2.2.3 on 2020-11-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0040_otpstorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
