# Generated by Django 2.2.3 on 2020-11-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0041_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='croplisting',
            name='crop_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
