# Generated by Django 2.2.3 on 2020-11-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmster_server', '0042_croplisting_crop_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croplisting',
            name='crop_count',
        ),
    ]
